# -*- coding: utf-8 -*-
"""Titanic data analysisETL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RddoF0Hu06Txr8hhLEcxRshCuGttbTZ9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

"""What was the overall survival rate?"""

df['Survived'].value_counts()

"""How many passengers were in each class (Pclass)?"""

class_count = df['Pclass'].value_counts()
print(class_count)

"""Did gender play a role in survival? (Survival rate by Sex)"""

gender_survival = df.groupby('Sex')['Survived'].mean()
print(gender_survival)

"""What was the survival rate based on Passenger Class?"""

class_survival = df.groupby('Pclass')['Survived'].mean()
print(class_survival)

"""What was the average age of survivors vs. non-survivors?"""

avg_age = df.groupby('Survived')['Age'].mean()
print(avg_age)

"""Which embarkation port had the highest survival rate?"""

Embarked_survived = df.groupby('Embarked')['Survived'].mean()
print(Embarked_survived)

"""How many missing values are in each column?"""

missing_data = df.isnull().sum()
print(missing_data)

"""What was the survival rate of "Women and Children" vs. Men?"""

df['adult_male'] = (df['Sex'] == 'male') & (df['Age']>=18)
compare = df.groupby('adult_male')['Survived'].mean()
print(compare)

"""Is there a correlation between Fare price and Survival?"""

correlation = df['Fare'].corr(df['Survived'])
print(f"correlation between Fare price and Survival : {correlation:.2f}%")

"""How many passengers traveled alone vs. with family?"""

df['family_size'] = df['SibSp'] + df['Parch']
df['alone']= df['family_size'] == 0
alone_counts = df['alone'].value_counts()
print(alone_counts)

sns.countplot(x='Survived', data=df)
plt.show()

sns.barplot(x='Sex', y='Survived', data=df)
plt.show()

"""Data Cleaning"""

df['Age'].fillna(df['Age'].mean(),inplace=True)
df.drop('Cabin', axis=1, inplace=True)

"""We’ll predict: Who survived Titanic"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

x= df[['Age', 'Fare']]
y = df['Survived']

x = x.fillna(x.mean())
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

model = LogisticRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)
accuracy = accuracy_score(y_test, pred)
print(f"Accuracy: {accuracy:.2f}")

